---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/connection.yaml

################################################################
## waiting for service running via port checking
################################################################

- name: Check the target ports to ensure valid state
  hosts: local
  become: true
  become_user: "{{ webmethods_user }}"
  tasks:
    - include_role:
        name: check-remote-ports
      vars:
        rvar_validation_host: "{{ vars_validation_host }}"
        rvar_validation_ports: "{{ vars_validation_ports }}"
        rvar_validation_ports_timeout: "{{ vars_validation_ports_timeout }}"
        rvar_async_timeout: "{{ common_async_timeout }}"
        rvar_async_poll: "{{ common_async_poll }}"
        rvar_async_retries: "{{ common_async_retries }}"
        rvar_async_delay: "{{ common_async_delay }}"