---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/settings_promotion_stages.yaml

################################################################
## set configs via REST APIs
################################################################

- name: System config tasks
  hosts: local
  become: true
  become_user: "{{ webmethods_user }}"
  run_once: true
  vars:
    apigateway_rest_protocol: "{{ vars_rest_protocol }}"
    apigateway_rest_host: "{{ vars_rest_host }}"
    apigateway_rest_port: "{{ vars_rest_port }}"
    apigateway_rest_no_check_certs: "{{ vars_rest_no_check_certs }}"
    apigateway_rest_login_username: "{{ vars_rest_login_username }}"
    apigateway_rest_login_password: "{{ vars_rest_login_password }}"

  tasks:

    - ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - _index_items_regex_pattern
        - _index_items
    
    - name: set initial list so it's not undefined
      set_fact:
         _promotions_stages_list: []

    - name: append each item template to list
      set_fact:
        _promotions_stages_list: "{{ _promotions_stages_list + [ _promotions_stages_template ] }}"
      loop: "{{ _index_items }}"
      loop_control:
        loop_var: index_item

    - ansible.builtin.debug:
        var: _promotions_stages_list

    - include_role:
        name: apigateway-rest-configurator
      vars:
        configs_action: set-promotion-stages
        configs_enabled: "{{ vars_promotions_stages_enabled }}"
        webmethods_apigateway_promotions_stages: "{{ _promotions_stages_list }}"