---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/data_packages.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  become: true
  become_user: "{{ webmethods_user }}"
  run_once: true
  vars:
    apigateway_rest_protocol: "{{ vars_rest_protocol }}"
    apigateway_rest_host: "{{ vars_rest_host }}"
    apigateway_rest_port: "{{ vars_rest_port }}"
    apigateway_rest_no_check_certs: "{{ vars_rest_no_check_certs }}"
    apigateway_rest_login_username: "{{ vars_rest_login_username }}"
    apigateway_rest_login_password: "{{ vars_rest_login_password }}"

  tasks:

    - name: set initial vars
      set_fact:
        _index_items_regex_pattern: "{{ _packages_publish_indices_regex_pattern }}"
        _publish_packages_list: []

    - ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - _index_items_regex_pattern
        - _index_items

    - name: append each item to list
      include_tasks: "publish_packages_append_each.yaml"
      loop: "{{ _index_items }}"
      loop_control:
        loop_var: index_item

    - ansible.builtin.debug:
        var: _publish_packages_list

    - include_role:
        name: apigateway-rest-configurator
      vars:
        configs_action: publish-packages-groups
        configs_enabled: "{{ vars_packages_publish_groups_enabled }}"
        rvar_apigateway_packages_publish_groups: "{{ _publish_packages_list }}"
